### ISSUE TITLE
Link in About and README goes to 404.

### ISSUE THREAD

**Issue by theantichris** [theartofeducation/ui-common#5]
<img width="349" alt="Screen Shot 2020-10-30 at 8 06 50 AM" src="https://user-images.githubusercontent.com/1486502/97703380-e8497480-1a86-11eb-8a45-85505b4178b3.png">

**Comment by ryexley** [comment]
I fixed the link in the About section on the site, and I'll fix the README in the open working branch that I have going right now.

**Comment by theantichris** [comment]
@ryexley just link this issue to that branch/pull request when ready.

**Comment by ryexley** [comment]
I forgot do link this issue and close it with that PR. This has been fixed.
